###

POST http://localhost:4010/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "carlos bensz",
    "age": "78",
    "email": "sccysLQ@gmail.com"
}

###
GET httpi://localhost:4010/api/users HTTP/1.1

###
GET http://localhost:4010/api/users/63721e7b0c8b72749630285f HTTP/1.1

###

PUT http://localhost:4010/api/users/637230f427a8b9cf34237b36 HTTP/1.1
Content-Type: application/json

{
    "name": "Brdonce Sterling",
    "age": 98,
    "email": "hackers@gmail.com"
}

###
DELETE http://localhost:4010/api/users/637230f427a8b9cf34237b36 HTTP/1.1
